name: Build and deploy Next.js 15 app to Azure Web App - squadflowaistudio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Next.js
        run: |
          npm install
          npm run build

      - name: Zip production build output for deployment
        run: |
          zip -r release.zip .next package.json next.config.js public

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # For Azure login token
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_429113E8EF9F4C7782A8F72E6248693C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1675C6A12384D73970D82F35E5A2D5E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBF23DF114B544B0AB4E730F981FE45C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'squadflowaistudio'
          slot-name: 'Production'
          package: '.'

      - name: Configure startup command on Azure App Service
        run: |
          az webapp config set --resource-group YOUR_RESOURCE_GROUP --name squadflowaistudio --startup-file "npx next start -p $PORT"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_429113E8EF9F4C7782A8F72E6248693C }}
          AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1675C6A12384D73970D82F35E5A2D5E }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBF23DF114B544B0AB4E730F981FE45C }}
